#!/bin/bash

GREEN='\033[0;32m'
NC='\033[0m' # No Color
echo -e ${GREEN}Downloading and installing Miniconda...${NC}
hash wget 2>/dev/null || { echo >&2 "This process requires wget but it's not installed."; read -p "Press ENTER to abort"; echo "Aborting."; exit 1; }
# wget https://repo.anaconda.com/archive/Anaconda3-2023.07-1-Linux-x86_64.sh
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
prefix=""
if [[ $(hostname -f) != *"uni-saarland.de" ]]; then
    read -ep $'Miniconda3 will now be installed into this location:\n/home/CE/manuelj/anaconda3\n\nPress enter to confirm or specify another location: ' prefix
    if [ $prefix != $'\n' ]; then 
        bash Miniconda3-latest-Linux-x86_64.sh -bp $prefix
    else
        bash Miniconda3-latest-Linux-x86_64.sh -b
    fi
else
    echo -e ${GREEN}host is uni.saarland.de, installing Miniconda3 in /local/$USER/miniconda3${NC}
    bash Miniconda3-latest-Linux-x86_64.sh -bp /local/$USER/miniconda3
fi
rm -f Miniconda3-latest-Linux-x86_64.sh
source ~/.bashrc 
export PATH=$prefix/bin:$PATH
echo -e ${GREEN}Looking for Miniconda updates...${NC}
conda update conda
echo -e ${GREEN}Creating miniconda environment "dl-in-dh"...${NC}
conda env create --file environment.yml
conda activate dl-in-dh

