#!/bin/bash

GREEN='\033[0;32m'
NC='\033[0m' # No Color
echo -e ${GREEN}Downloading and installing Anaconda...${NC}
hash wget 2>/dev/null || { echo >&2 "This process requires wget but it's not installed."; read -p "Press ENTER to abort"; echo "Aborting."; exit 1; }
wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
prefix=""
if [[ $(hostname -f) != *"uni-saarland.de" ]]; then
    read -ep $'Anaconda3 will now be installed into this location:\n${HOME}anaconda3\n\nPress enter to confirm or specify another location: ' prefix
    if [ $prefix != $'\n' ]; then 
        bash Anaconda3-latest-Linux-x86_64.sh -bp $prefix
    else
        bash Anaconda3-latest-Linux-x86_64.sh -b
    fi
else
    echo -e ${GREEN}host is uni.saarland.de, installing Anaconda3 in /local/$USER/anaconda3${NC}
    bash Anaconda3-latest-Linux-x86_64.sh -bp /local/$USER/anaconda3
    prefix="/local/$USER/anaconda3"
fi
rm -f Anaconda3-latest-Linux-x86_64.sh
source ~/.bashrc 
export PATH=$prefix/bin:$PATH
echo -e ${GREEN}Looking for Anaconda3 updates...${NC}
conda update conda
echo -e ${GREEN}Creating anaconda environment "dl-in-dh"...${NC}
conda env create --file environment.yml
conda activate dl-in-dh

